apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledger-light
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ledger-light.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ledger-light
                port:
                  number: 80
