apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ledgerlight
  namespace: ledgerlight
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  ingressClassName: nginx
  rules:
    - host: ledgerlight.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ledgerlight-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ledgerlight-frontend
                port:
                  name: http

