apiVersion: v1
kind: Service
metadata:
  name: ledgerlight-api
  namespace: ledgerlight
spec:
  selector:
    app.kubernetes.io/name: ledgerlight-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ledgerlight-frontend
  namespace: ledgerlight
spec:
  selector:
    app.kubernetes.io/name: ledgerlight-frontend
  ports:
    - name: http
      port: 80
      targetPort: http

