name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-api:
    uses: raolivei/github-workflows/.github/workflows/docker-build.yml@main
    with:
      image-name: canopy-api
      context: ./backend
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-frontend:
    uses: raolivei/github-workflows/.github/workflows/docker-build.yml@main
    with:
      image-name: canopy-frontend
      context: ./frontend
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
